"""Curiosity Engine — anomaly detection and exploration drive.

Curiosity is what transforms a passive memory system into an active learner.
Biological curiosity has two components:
  - D-curiosity (diversive): general exploration, novelty-seeking
  - S-curiosity (specific): driven by information gaps, need-to-know

This module implements both. Mnemosyne becomes curious when:
1. Something doesn't match what it expected (prediction error)
2. A knowledge gap is detected (knows partial info, not the full picture)
3. Contradictions exist in memory (inconsistent beliefs)
4. A pattern breaks (established rhythm changes)
5. Novel topics appear (never seen before)

Curiosity generates questions, drives exploration during idle time,
and feeds back into the goal system as intrinsic motivation.
"""

from __future__ import annotations

import logging
import math
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import numpy as np

logger = logging.getLogger("mnemosyne.consciousness.curiosity")


class CuriosityType:
    PREDICTION_ERROR = "prediction_error"  # Reality didn't match expectation
    KNOWLEDGE_GAP = "knowledge_gap"        # Partial knowledge, missing pieces
    CONTRADICTION = "contradiction"        # Conflicting beliefs in memory
    NOVELTY = "novelty"                    # Never encountered before
    PATTERN_BREAK = "pattern_break"        # Established pattern violated


@dataclass
class CuriositySignal:
    """A specific thing Mnemosyne is curious about."""
    curiosity_type: str
    description: str
    intensity: float              # 0-1, how curious (drives exploration priority)
    generated_questions: list[str] = field(default_factory=list)
    source_entry_ids: list[int] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    resolved: bool = False
    resolution: Optional[str] = None

    @property
    def age_hours(self) -> float:
        try:
            created = datetime.fromisoformat(self.created_at)
            if created.tzinfo is None:
                created = created.replace(tzinfo=timezone.utc)
            return (datetime.now(timezone.utc) - created).total_seconds() / 3600
        except (ValueError, TypeError):
            return 0.0

    @property
    def urgency(self) -> float:
        """Curiosity that isn't resolved becomes more urgent over time, then fades."""
        if self.resolved:
            return 0.0
        age = self.age_hours
        # Bell curve: peaks at ~6 hours, fades after 72
        return self.intensity * math.exp(-((age - 6) ** 2) / (2 * 24 ** 2))


@dataclass
class ExpectationModel:
    """A learned expectation that can generate prediction errors."""
    pattern: str                  # What we expect
    confidence: float             # How sure we are
    observation_count: int = 0    # How many times confirmed
    last_confirmed: Optional[str] = None
    last_violated: Optional[str] = None


class CuriosityEngine:
    """Detects anomalies and generates exploration drives.

    Maintains a model of expectations and fires curiosity signals
    whenever reality diverges from expectation.
    """

    def __init__(
        self,
        novelty_threshold: float = 0.3,
        contradiction_threshold: float = 0.6,
        max_active_signals: int = 20,
    ):
        self.novelty_threshold = novelty_threshold
        self.contradiction_threshold = contradiction_threshold
        self.max_active_signals = max_active_signals

        self.active_signals: list[CuriositySignal] = []
        self.resolved_signals: deque[CuriositySignal] = deque(maxlen=100)
        self.expectations: list[ExpectationModel] = []

        # Embedding history for novelty detection
        self._embedding_history: deque[np.ndarray] = deque(maxlen=500)
        self._topic_counts: dict[str, int] = {}

    def observe(
        self,
        content: str,
        embedding: Optional[np.ndarray] = None,
        existing_memories: Optional[list[tuple[str, float]]] = None,
    ) -> list[CuriositySignal]:
        """Observe new input and generate curiosity signals.

        Args:
            content: The new input text
            embedding: Its embedding vector
            existing_memories: List of (content, similarity) from retrieval

        Returns:
            New curiosity signals generated by this observation.
        """
        signals = []

        # 1. Novelty detection
        if embedding is not None:
            novelty_signal = self._detect_novelty(content, embedding)
            if novelty_signal:
                signals.append(novelty_signal)

        # 2. Knowledge gap detection
        if existing_memories:
            gap_signal = self._detect_knowledge_gap(content, existing_memories)
            if gap_signal:
                signals.append(gap_signal)

        # 3. Contradiction detection
        if existing_memories:
            contradiction_signal = self._detect_contradictions(content, existing_memories)
            if contradiction_signal:
                signals.append(contradiction_signal)

        # 4. Prediction error
        error_signal = self._check_expectations(content)
        if error_signal:
            signals.append(error_signal)

        # Store new signals
        for signal in signals:
            self.active_signals.append(signal)
            logger.info(
                f"Curiosity [{signal.curiosity_type}] (intensity={signal.intensity:.2f}): "
                f"{signal.description[:80]}"
            )

        # Track embedding for future novelty detection
        if embedding is not None:
            self._embedding_history.append(embedding)

        # Track topic frequency
        words = content.lower().split()
        for word in words:
            if len(word) > 4:  # Only track meaningful words
                self._topic_counts[word] = self._topic_counts.get(word, 0) + 1

        # Prune old signals
        self._prune_signals()

        return signals

    def get_burning_questions(self, n: int = 3) -> list[str]:
        """Return the top questions Mnemosyne wants answered.

        These can be surfaced to the user proactively or pursued
        during dream consolidation.
        """
        # Sort by urgency
        active = [s for s in self.active_signals if not s.resolved]
        active.sort(key=lambda s: s.urgency, reverse=True)

        questions = []
        for signal in active[:n]:
            questions.extend(signal.generated_questions[:2])

        return questions[:n]

    def resolve(self, signal_index: int, resolution: str) -> None:
        """Mark a curiosity signal as resolved."""
        if 0 <= signal_index < len(self.active_signals):
            signal = self.active_signals[signal_index]
            signal.resolved = True
            signal.resolution = resolution
            self.resolved_signals.append(signal)

    def learn_expectation(self, pattern: str, confidence: float = 0.5) -> None:
        """Learn a new expectation that can later generate prediction errors."""
        self.expectations.append(ExpectationModel(
            pattern=pattern,
            confidence=confidence,
        ))

    def _detect_novelty(self, content: str, embedding: np.ndarray) -> Optional[CuriositySignal]:
        """Detect if this input is genuinely novel (far from anything seen before)."""
        if len(self._embedding_history) < 5:
            return None  # Not enough history to judge

        # Compute similarity to all past embeddings
        history = np.stack(list(self._embedding_history))
        norms = np.linalg.norm(history, axis=1, keepdims=True)
        norms = np.where(norms < 1e-10, 1.0, norms)
        normed_history = history / norms

        query_norm = np.linalg.norm(embedding)
        if query_norm < 1e-10:
            return None
        normed_query = embedding / query_norm

        similarities = normed_history @ normed_query
        max_similarity = float(np.max(similarities))

        if max_similarity < self.novelty_threshold:
            # This is genuinely novel — never seen anything like it
            intensity = 1.0 - max_similarity  # More novel = more intense
            return CuriositySignal(
                curiosity_type=CuriosityType.NOVELTY,
                description=f"Novel topic detected (max similarity to past: {max_similarity:.2f})",
                intensity=min(1.0, intensity),
                generated_questions=[
                    f"What is this about: {content[:100]}?",
                    "How does this connect to what I already know?",
                ],
            )

        return None

    def _detect_knowledge_gap(
        self,
        content: str,
        memories: list[tuple[str, float]],
    ) -> Optional[CuriositySignal]:
        """Detect partial knowledge — we know something related but not enough."""
        if not memories:
            return None

        # If top results are moderately similar (0.3-0.7), we have partial knowledge
        top_similarities = [sim for _, sim in memories[:5]]
        avg_sim = sum(top_similarities) / len(top_similarities)

        if 0.3 <= avg_sim <= 0.65:
            # We know something related, but not exactly this
            intensity = 0.6 * (1.0 - avg_sim)  # Less similar = bigger gap
            return CuriositySignal(
                curiosity_type=CuriosityType.KNOWLEDGE_GAP,
                description=f"Partial knowledge detected (avg similarity: {avg_sim:.2f})",
                intensity=min(1.0, intensity),
                generated_questions=[
                    f"I know something related, but what specifically about: {content[:80]}?",
                    "What am I missing that would complete my understanding?",
                ],
            )

        return None

    def _detect_contradictions(
        self,
        content: str,
        memories: list[tuple[str, float]],
    ) -> Optional[CuriositySignal]:
        """Detect when new input contradicts existing memories."""
        if not memories:
            return None

        # Simple heuristic: negation words near high-similarity memories
        negation_markers = {"not", "never", "wrong", "incorrect", "false", "isn't",
                           "wasn't", "don't", "doesn't", "changed", "no longer",
                           "actually", "contrary", "however", "but"}

        content_lower = content.lower()
        has_negation = any(marker in content_lower for marker in negation_markers)

        if has_negation:
            # Check if this is about something we have strong memories of
            top_sim = memories[0][1] if memories else 0.0
            if top_sim > self.contradiction_threshold:
                return CuriositySignal(
                    curiosity_type=CuriosityType.CONTRADICTION,
                    description=f"Possible contradiction with existing memory (similarity: {top_sim:.2f})",
                    intensity=0.8,
                    generated_questions=[
                        "Which version is correct — what I remember or this new information?",
                        "Has something changed, or was my earlier understanding wrong?",
                    ],
                )

        return None

    def _check_expectations(self, content: str) -> Optional[CuriositySignal]:
        """Check if content violates any learned expectations."""
        content_lower = content.lower()

        for exp in self.expectations:
            # Simple keyword check against expectations
            if exp.pattern.lower() in content_lower:
                exp.observation_count += 1
                exp.last_confirmed = datetime.now(timezone.utc).isoformat()
            # If content contains negation of the pattern
            elif any(f"not {word}" in content_lower for word in exp.pattern.lower().split()[:3]):
                exp.last_violated = datetime.now(timezone.utc).isoformat()
                if exp.confidence > 0.5:
                    return CuriositySignal(
                        curiosity_type=CuriosityType.PREDICTION_ERROR,
                        description=f"Expectation violated: '{exp.pattern}' (confidence was {exp.confidence:.2f})",
                        intensity=exp.confidence * 0.8,
                        generated_questions=[
                            f"Why did '{exp.pattern}' not hold this time?",
                            "Should I update my understanding?",
                        ],
                    )

        return None

    def _prune_signals(self) -> None:
        """Remove old, low-urgency signals."""
        # Remove resolved signals
        self.active_signals = [s for s in self.active_signals if not s.resolved]

        # If over capacity, remove lowest urgency
        if len(self.active_signals) > self.max_active_signals:
            self.active_signals.sort(key=lambda s: s.urgency, reverse=True)
            self.active_signals = self.active_signals[:self.max_active_signals]

    def get_curiosity_level(self) -> float:
        """Overall curiosity level (0-1). Drives exploration behavior."""
        if not self.active_signals:
            return 0.0
        urgencies = [s.urgency for s in self.active_signals]
        # Soft max — dominated by the most urgent signal but boosted by count
        max_urgency = max(urgencies)
        breadth_bonus = min(0.2, len(urgencies) * 0.02)
        return min(1.0, max_urgency + breadth_bonus)

    def get_stats(self) -> dict:
        active = [s for s in self.active_signals if not s.resolved]
        return {
            "active_signals": len(active),
            "resolved_signals": len(self.resolved_signals),
            "curiosity_level": self.get_curiosity_level(),
            "burning_questions": self.get_burning_questions(3),
            "expectations_learned": len(self.expectations),
            "topics_tracked": len(self._topic_counts),
            "top_signals": [
                {
                    "type": s.curiosity_type,
                    "description": s.description[:80],
                    "intensity": s.intensity,
                    "urgency": s.urgency,
                    "questions": s.generated_questions[:1],
                }
                for s in sorted(active, key=lambda s: s.urgency, reverse=True)[:3]
            ],
        }
